### ISSUE TITLE
Bug: no response to jupyter frontend 

### ISSUE THREAD

**Issue by vanabel** [WolframResearch/WolframLanguageForJupyter#147]
After a new install of WolframLanguageForJupyter on my nas, I can execute
```bash
base) root@jupyter-datascience-notebook1:~# wolframscript 
Wolfram Language 13.3.0 Engine for Linux x86 (64-bit)
Copyright 1988-2023 Wolfram Research, Inc.

In[1]:= $Version                                                                                                  
Out[1]= 13.3.0 for Linux x86 (64-bit) (June 12, 2023)

(base) root@jupyter-datascience-notebook1:~# WolframKernel 
Wolfram Language 13.3.0 Engine for Linux x86 (64-bit)
Copyright 1988-2023 Wolfram Research, Inc.

In[1]:= $Version                                                                                                  
Out[1]= 13.3.0 for Linux x86 (64-bit) (June 12, 2023)
```
This also work for other user, like `jovyan`. But it seems, in the `juypter lab` frontend, when I execute:1+2, it has no response.
The log file looks like:
```log
[I 2023-09-28 19:19:20.020 ServerApp] Kernel started: 05805916-2cbb-414d-a472-b8cc5e18ed5e
,[I 2023-09-28 19:19:20.566 ServerApp] Starting buffering for e887bdaa-b1af-4c2e-b4f4-2998e0c1f2b9:da7d4c2b-b984-4c5f-821f-b0e91dce0d19
,/home/jovyan/Wolfram/WolframEngine/13.3/SystemFiles/FrontEnd/Binaries/Linux-x86-64/WolframPlayer: error while loading shared libraries: libEGL.so.1: cannot open shared object file: No such file or directory
,[W 2023-09-28 19:20:21.084 ServerApp] Timeout waiting for kernel_info reply from 05805916-2cbb-414d-a472-b8cc5e18ed5e
,[W 2023-09-28 19:20:25.656 ServerApp] Nudge: attempt 10 on kernel 05805916-2cbb-414d-a472-b8cc5e18ed5e
,[W 2023-09-28 19:20:30.672 ServerApp] Nudge: attempt 20 on kernel 05805916-2cbb-414d-a472-b8cc5e18ed5e
,[W 2023-09-28 19:20:35.688 ServerApp] Nudge: attempt 30 on kernel 05805916-2cbb-414d-a472-b8cc5e18ed5e
,[W 2023-09-28 19:20:40.704 ServerApp] Nudge: attempt 40 on kernel 05805916-2cbb-414d-a472-b8cc5e18ed5e
,[W 2023-09-28 19:20:45.717 ServerApp] Nudge: attempt 50 on kernel 05805916-2cbb-414d-a472-b8cc5e18ed5e
,[W 2023-09-28 19:20:50.731 ServerApp] Nudge: attempt 60 on kernel 05805916-2cbb-414d-a472-b8cc5e18ed5e
,[W 2023-09-28 19:20:55.753 ServerApp] Nudge: attempt 70 on kernel 05805916-2cbb-414d-a472-b8cc5e18ed5e
,[W 2023-09-28 19:21:00.766 ServerApp] Nudge: attempt 80 on kernel 05805916-2cbb-414d-a472-b8cc5e18ed5e
,[W 2023-09-28 19:21:05.784 ServerApp] Nudge: attempt 90 on kernel 05805916-2cbb-414d-a472-b8cc5e18ed5e
,[W 2023-09-28 19:21:10.798 ServerApp] Nudge: attempt 100 on kernel 05805916-2cbb-414d-a472-b8cc5e18ed5e
,[W 2023-09-28 19:21:15.811 ServerApp] Nudge: attempt 110 on kernel 05805916-2cbb-414d-a472-b8cc5e18ed5e
,[W 2023-09-28 19:21:20.831 ServerApp] Nudge: attempt 120 on kernel 05805916-2cbb-414d-a472-b8cc5e18ed5e
,[E 2023-09-28 19:21:21.089 ServerApp] Uncaught exception GET /api/kernels/05805916-2cbb-414d-a472-b8cc5e18ed5e/channels?session_id=18228c10-f294-43ea-80e0-2b615dce92e5 (192.168.8.254)
,    HTTPServerRequest(protocol='http', host='jupyter.xxxx.cn', method='GET', uri='/api/kernels/05805916-2cbb-414d-a472-b8cc5e18ed5e/channels?session_id=18228c10-f294-43ea-80e0-2b615dce92e5', version='HTTP/1.1', remote_ip='192.168.8.254')
,    Traceback (most recent call last):
,      File "/opt/conda/lib/python3.10/site-packages/tornado/websocket.py", line 956, in _accept_connection
,      File "/opt/conda/lib/python3.10/asyncio/tasks.py", line 304, in __wakeup
,        await open_result
,        future.result()
,    tornado.util.TimeoutError: Timeout
,[E 2023-09-28 19:21:21.129 ServerApp] Uncaught exception GET /api/kernels/05805916-2cbb-414d-a472-b8cc5e18ed5e/channels?session_id=61a58b04-8b36-49e6-a0e8-193d2a3c0371 (192.168.8.254)
,    HTTPServerRequest(protocol='http', host='jupyter.xxxx.cn', method='GET', uri='/api/kernels/05805916-2cbb-414d-a472-b8cc5e18ed5e/channels?session_id=61a58b04-8b36-49e6-a0e8-193d2a3c0371', version='HTTP/1.1', remote_ip='192.168.8.254')
,[E 2023-09-28 19:21:21.132 ServerApp] Uncaught exception GET /api/kernels/05805916-2cbb-414d-a472-b8cc5e18ed5e/channels?session_id=da7d4c2b-b984-4c5f-821f-b0e91dce0d19 (192.168.8.254)
,    HTTPServerRequest(protocol='http', host='jupyter.xxxx.cn', method='GET', uri='/api/kernels/05805916-2cbb-414d-a472-b8cc5e18ed5e/channels?session_id=da7d4c2b-b984-4c5f-821f-b0e91dce0d19', version='HTTP/1.1', remote_ip='192.168.8.254')
,[E 2023-09-28 19:21:21.134 ServerApp] Uncaught exception GET /api/kernels/05805916-2cbb-414d-a472-b8cc5e18ed5e/channels?session_id=06f7bc20-6fcb-43c8-b215-fb3d194c991c (192.168.8.254)
,    HTTPServerRequest(protocol='http', host='jupyter.xxxx.cn', method='GET', uri='/api/kernels/05805916-2cbb-414d-a472-b8cc5e18ed5e/channels?session_id=06f7bc20-6fcb-43c8-b215-fb3d194c991c', version='HTTP/1.1', remote_ip='192.168.8.254')
,[W 2023-09-28 19:21:21.891 ServerApp] Replacing stale connection: 05805916-2cbb-414d-a472-b8cc5e18ed5e:da7d4c2b-b984-4c5f-821f-b0e91dce0d19
,[W 2023-09-28 19:21:21.941 ServerApp] Replacing stale connection: 05805916-2cbb-414d-a472-b8cc5e18ed5e:06f7bc20-6fcb-43c8-b215-fb3d194c991c
,[W 2023-09-28 19:23:02.492 ServerApp] Replacing stale connection: 05805916-2cbb-414d-a472-b8cc5e18ed5e:18228c10-f294-43ea-80e0-2b615dce92e5
,[I 2023-09-28 19:23:02.084 ServerApp] Starting buffering for 05805916-2cbb-414d-a472-b8cc5e18ed5e:61a58b04-8b36-49e6-a0e8-193d2a3c0371
,[W 2023-09-28 19:21:22.090 ServerApp] Replacing stale connection: 05805916-2cbb-414d-a472-b8cc5e18ed5e:61a58b04-8b36-49e6-a0e8-193d2a3c0371
,[W 2023-09-28 19:21:22.048 ServerApp] Replacing stale connection: 05805916-2cbb-414d-a472-b8cc5e18ed5e:18228c10-f294-43ea-80e0-2b615dce92e5
,[I 2023-09-28 19:34:07.495 ServerApp] 302 GET / (192.168.8.254) 0.68ms
,[I 2023-09-28 19:34:10.331 ServerApp] 302 GET / (192.168.8.254) 0.65ms
,[W 2023-09-28 19:35:03.321 ServerApp] Replacing stale connection: 05805916-2cbb-414d-a472-b8cc5e18ed5e:61a58b04-8b36-49e6-a0e8-193d2a3c0371
```
while I use SageMath, to execute 1+2, it return the results correctly and the log looks like:
```log
[I 2023-09-28 19:14:04.021 ServerApp] Kernel started: e887bdaa-b1af-4c2e-b4f4-2998e0c1f2b9
,[I 2023-09-28 19:14:17.435 ServerApp] Adapting from protocol version 5.0 (kernel e887bdaa-b1af-4c2e-b4f4-2998e0c1f2b9) to 5.3 (client).
,[I 2023-09-28 19:14:17.437 ServerApp] Adapting from protocol version 5.0 (kernel e887bdaa-b1af-4c2e-b4f4-2998e0c1f2b9) to 5.3 (client).
,[I 2023-09-28 19:14:17.438 ServerApp] Adapting from protocol version 5.0 (kernel e887bdaa-b1af-4c2e-b4f4-2998e0c1f2b9) to 5.3 (client).
```

**Comment by vanabel** [comment]
BTW, my juputer version is:
```jupyter
!jupyter --version
```
```bash
Selected Jupyter core packages...
IPython          : 8.5.0
ipykernel        : 6.16.0
ipywidgets       : 8.0.2
jupyter_client   : 7.3.4
jupyter_core     : 4.11.1
jupyter_server   : 1.21.0
jupyterlab       : 3.4.8
nbclient         : 0.7.0
nbconvert        : 7.2.1
nbformat         : 5.7.0
notebook         : 6.5.1
qtconsole        : not installed
traitlets        : 5.4.0
```

**Comment by vanabel** [comment]
The issue is solve by installing `apt-get install -y libegl1-mesa` on my docker image, which is based on Ubuntu.
