### ISSUE TITLE
Problem with wolframscript

### ISSUE THREAD

**Issue by Dario-Rosa85** [WolframResearch/WolframLanguageForJupyter#90]
I am trying to follow the steps outlined in 

Method 1: Using `wolframscript`

I have a windows machine. However, I get this problem

`C:\Users\dario\OneDrive\Desktop\WolframLanguageForJupyter-master>.\configure-jupyter.wls add "C:\Program Files\Wolfram Research\Mathematica\12.1\WolframKernel.exe" "C:\Users\dario\Anaconda3\Scripts\jupyter.exe"
configure-jupyter.wls: An error has occurred. The desired Wolfram Engine is not in "jupyter kernelspec list."
configure-jupyter.wls: See below for the message that Jupyter returned when attempting to add the Wolfram Engine.
Traceback (most recent call last):
  File "C:\Users\dario\Anaconda3\Scripts\jupyter-kernelspec-script.py", line 5, in <module>
    from jupyter_client.kernelspecapp import KernelSpecApp
  File "C:\Users\dario\Anaconda3\lib\site-packages\jupyter_client\__init__.py", line 4, in <module>
    from .connect import *
  File "C:\Users\dario\Anaconda3\lib\site-packages\jupyter_client\connect.py", line 21, in <module>
    import zmq
  File "C:\Users\dario\Anaconda3\lib\site-packages\zmq\__init__.py", line 47, in <module>
    from zmq import backend
  File "C:\Users\dario\Anaconda3\lib\site-packages\zmq\backend\__init__.py", line 40, in <module>
    reraise(*exc_info)
  File "C:\Users\dario\Anaconda3\lib\site-packages\zmq\utils\sixcerpt.py", line 34, in reraise
    raise value
  File "C:\Users\dario\Anaconda3\lib\site-packages\zmq\backend\__init__.py", line 27, in <module>
    _ns = select_backend(first)
  File "C:\Users\dario\Anaconda3\lib\site-packages\zmq\backend\select.py", line 28, in select_backend
    mod = __import__(name, fromlist=public_api)
  File "C:\Users\dario\Anaconda3\lib\site-packages\zmq\backend\cython\__init__.py", line 6, in <module>
    from . import (constants, error, message, context,
ImportError: DLL load failed: The specified module could not be found. `

Anybody can help me?

**Comment by Dario-Rosa85** [comment]
I fixed: I guess the problem was related to my jupyter installed through Anaconda. I removed anaconda and installed jupyter via pip and now everything is working fine.
