### ISSUE TITLE
Jupyter configuration failed

### ISSUE THREAD

**Issue by JuergenKanz** [WolframResearch/WolframLanguageForJupyter#99]
Hi, 

the Jupyter configuration on my Windows 10 PC fails. I am using Windows 10 and Anaconda3 each with the latest updates. In parallel Mathematica 12.1.1 is installed. The "WolframLanguageForJupyter-0.9.2.paclet" is in use.

I get the following messages:

" In[1]:= Needs["WolframLanguageForJupyter`"]

In[2]:= ConfigureJupyter["Add"]
Traceback (most recent call last):
  File "c:\Users\juerg\anaconda3\Scripts\jupyter-kernelspec-script.py", line 5, in <module>
    from jupyter_client.kernelspecapp import KernelSpecApp
  File "c:\Users\juerg\anaconda3\lib\site-packages\jupyter_client\__init__.py", line 4, in <module>
    from .connect import *
  File "c:\Users\juerg\anaconda3\lib\site-packages\jupyter_client\connect.py", line 21, in <module>
    import zmq
  File "c:\Users\juerg\anaconda3\lib\site-packages\zmq\__init__.py", line 50, in <module>
    from zmq import backend
  File "c:\Users\juerg\anaconda3\lib\site-packages\zmq\backend\__init__.py", line 40, in <module>
    reraise(*exc_info)
  File "c:\Users\juerg\anaconda3\lib\site-packages\zmq\utils\sixcerpt.py", line 34, in reraise
    raise value
  File "c:\Users\juerg\anaconda3\lib\site-packages\zmq\backend\__init__.py", line 27, in <module>
    _ns = select_backend(first)
  File "c:\Users\juerg\anaconda3\lib\site-packages\zmq\backend\select.py", line 28, in select_backend
    mod = __import__(name, fromlist=public_api)
  File "c:\Users\juerg\anaconda3\lib\site-packages\zmq\backend\cython\__init__.py", line 6, in\
 
>   <module>
    from . import (constants, error, message, context,
ImportError: DLL load failed while importing error: Das angegebene Modul wurde nicht gefunden.

ConfigureJupyter::notadded: 
   An error has occurred. The desired Wolfram Engine is not in "jupyter kernelspec list." See
    WolframLanguageForJupyter`Errors`$ConfigureError for the message that Jupyter returned when
    attempting to add the Wolfram Engine.

Out[2]= $Failed "

What to do?

**Comment by JuergenKanz** [comment]
The problem does still exist. 

No problem to add Julia and Octave.

**Comment by cc-wr** [comment]
@JuergenKanz, have you looked through the following thread?

https://github.com/jupyter/notebook/issues/4332

Additionally, what happens if you just try to run `jupyter notebook` in `cmd.exe` (or through Anaconda)? If you also get the issue there, that would suggest that the problem is not on the WolframLanguageForJupyter side.

**Comment by JuergenKanz** [comment]
Thanks for the hints. Finally, I could solve the problem in two steps.

1. To run "jupyter notebook" in the **Anconda3 prompt** was not a problem. To do the same in **cmd** led to a fatal error first (see screenshot below). It was possible to solve it by the installation of Cygwin64 incl. GCC-core.
![2020-12-09 12_41_13-Window](https://user-images.githubusercontent.com/65070344/101641799-7c1d4180-3a32-11eb-8878-4efaefaa71bd.png)

2. Additional entries in PATH were needed:
...\Anaconda3\Scripts
...\Anaconda3\Library\Bin
...\Anaconda3\condabin

and as mentioned above ..\cygwin64\bin

The Wolfram Engine is now perfectly running with Jupyter!
